name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip ci') }}
    steps:
      - run: echo "github.event.pull_request.labels.*.name ${{ github.event.pull_request.labels.*.name }}"
